Traceback (most recent call last):
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/run_experiments.py", line 113, in run_all_experiments
    results = run_model_and_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 474, in run_model_and_evaluate
    params, expected = model.fit(x_data, y_data, x_aux, n_iter=max_iters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 289, in fit
    params = self.initialize_parameters(X, Y, X_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 122, in initialize_parameters
    X_aux @ gamma_mean[None, :])  # (n, kappa)
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 579, in deferring_binary_op
    return binary_op(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/tensor_contractions.py", line 243, in matmul
    out = lax.dot_general(
          ^^^^^^^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (2,) and (1,).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Traceback (most recent call last):
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/run_experiments.py", line 113, in run_all_experiments
    results = run_model_and_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 474, in run_model_and_evaluate
    params, expected = model.fit(x_data, y_data, x_aux, n_iter=max_iters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 289, in fit
    params = self.initialize_parameters(X, Y, X_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 122, in initialize_parameters
    X_aux @ gamma_mean[None, :])  # (n, kappa)
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 579, in deferring_binary_op
    return binary_op(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/tensor_contractions.py", line 243, in matmul
    out = lax.dot_general(
          ^^^^^^^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (2,) and (1,).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Traceback (most recent call last):
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/run_experiments.py", line 113, in run_all_experiments
    results = run_model_and_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 474, in run_model_and_evaluate
    params, expected = model.fit(x_data, y_data, x_aux, n_iter=max_iters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 289, in fit
    params = self.initialize_parameters(X, Y, X_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 122, in initialize_parameters
    X_aux @ gamma_mean[None, :])  # (n, kappa)
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 579, in deferring_binary_op
    return binary_op(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/tensor_contractions.py", line 243, in matmul
    out = lax.dot_general(
          ^^^^^^^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (2,) and (1,).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Traceback (most recent call last):
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/run_experiments.py", line 113, in run_all_experiments
    results = run_model_and_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 474, in run_model_and_evaluate
    params, expected = model.fit(x_data, y_data, x_aux, n_iter=max_iters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 289, in fit
    params = self.initialize_parameters(X, Y, X_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 122, in initialize_parameters
    X_aux @ gamma_mean[None, :])  # (n, kappa)
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 579, in deferring_binary_op
    return binary_op(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/tensor_contractions.py", line 243, in matmul
    out = lax.dot_general(
          ^^^^^^^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (2,) and (1,).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
Traceback (most recent call last):
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/run_experiments.py", line 113, in run_all_experiments
    results = run_model_and_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 474, in run_model_and_evaluate
    params, expected = model.fit(x_data, y_data, x_aux, n_iter=max_iters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 289, in fit
    params = self.initialize_parameters(X, Y, X_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/labs/Aguiar/SSPA_BRAY/BRay/VariationalInference/vi_model_complete.py", line 122, in initialize_parameters
    X_aux @ gamma_mean[None, :])  # (n, kappa)
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 579, in deferring_binary_op
    return binary_op(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/FCAM/tyasenpoor/miniconda3/envs/bray_cpu/lib/python3.11/site-packages/jax/_src/numpy/tensor_contractions.py", line 243, in matmul
    out = lax.dot_general(
          ^^^^^^^^^^^^^^^^
TypeError: dot_general requires contracting dimensions to have the same shape, got (2,) and (1,).
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
slurmstepd: error: *** JOB 9226852 ON xanadu-39 CANCELLED AT 2025-07-13T19:05:21 ***
